language: java
jdk:
  - oraclejdk8

before_script:
  - wget https://github.com/mouserd/microservice-commons/releases/download/1.0.0/microservice-commons-1.0.0.jar -O /home/travis/.m2/repository/com/pixelus/microservice-commons/1.0.0/microservice-commons-1.0.0.jar