info:
  component: Player (Local Properties)

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    refresh:
      interval: 5

hystrix:
  enabled: true
  streamEnabled: true
  streamUrl: /hystrix.stream
  stream:
    bus:
      enabled: true
      sendRate: 600

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost/player-service
    username: player-service
    password: abc123
    driver-class-name: com.mysql.jdbc.Driver

endpoints:
  health:
    sensitive: false